### ISSUE TITLE
No Makefile in the directory after running configure script

### ISSUE THREAD

**Issue by dkopotev** [forflo/yodl#3]
Hi Florian,

First of all thank you for starting this project!

I've tried to install it and unfortunately was stopped at the first step. After I ran
`./configure`
at my system I was not able to find any Makefile in the projects directory.

I am not waiting that you completely solve my problem, but could you please give some hints where to search for the issue? Probably with your 5 minutes time you can save me hours.

The config.log is attached (zipped):
[config.zip](https://github.com/forflo/yodl/files/751446/config.zip)

Thank you in advance.
Best regards,
Dmitry

**Comment by forflo** [comment]
> First of all thank you for starting this project!

You're very welcome.

Sorry for letting you wait so long. I was travelling, but now I'm back.
Please, give me some time to look into your problem.

Best regards

**Comment by forflo** [comment]
Ok, where exactly did you run `./configure`?

... or have you found a solution by yourself already?

**Comment by dkopotev** [comment]
Hi Florian,

No, I haven't found the solution so far. I started the script in one of the home directories:

~/projects/fpga/software/yodl-master

with a command:

sudo ./configure

Do you thing that the issue is related to the directory I try to run it in?
Where should I try to run the ./configure script then?

Best regards,
Dmitry

**Comment by Piressss** [comment]
I also have the same issue. 

I ran the ./configure, and after I try to run make, but I got this message:

make: *** No targets specified and no makefile found.  Stop.

**Comment by befedo** [comment]
I think [INSTALL](https://github.com/forflo/yodl/blob/2cd547a51bdb38c1ad974a73c3d9e448d28bab6e/INSTALL) is a bit confusing here.

After running `./configure` inside the root directory of the repo (doesn't require root access when inside `$HOME` thus `sudo` isn't neccessary) you could run `./config.status` to see what happened.
```
[foo@bar yodl]$ ./config.status 
config.status: creating vhdlpp/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: creating vhdlpp/vhdlpp_config.h
config.status: vhdlpp/vhdlpp_config.h is unchanged
```
This tells you that a `Makefile` was created inside the `vhdlpp` subdirectory.

If you run `make`, `make check` and `make install` there everything should be fine.

### Edit:
You should also have a look at this [comment](https://github.com/forflo/yodl/issues/1#issuecomment-246173793) and `patch` the sources with the hotfix.

```
[foo@bar yodl]$ patch --verbose vhdlpp/main.cc yodl-main-hotfix.txt 
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/vhdlpp/main.cc b/vhdlpp/main.cc
|index 8e3f72d..2d864b0 100644
|--- a/vhdlpp/main.cc
|+++ b/vhdlpp/main.cc
--------------------------
patching file vhdlpp/main.cc
Using Plan A...
Hunk #1 succeeded at 21.
Hunk #2 succeeded at 81.
Hunk #3 succeeded at 247.
done

```

**Comment by dkopotev** [comment]
Hi befedo,

Thanks for the explanation! I was able to successfully compile the program. The ticket can be closed.

Best regards,
Dmitry
